name: Build Docker Image

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build Docker image
      run: |
        docker build -t task-manager:test .
        
    - name: Test Docker image
      run: |
        # 测试镜像是否能正常导入模块
        docker run --rm task-manager:test python -c "import sys; sys.path.append('/app/src'); from task import Task; print('✅ Task class imported successfully')"
